1. Create a vector with values ranging from 10 to 49.

In [26]:
import numpy as np
vector = np.arange(10, 50)
print("Vector:", vector)

Vector: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3x3 matrix with values ranging from 0 to 8.

In [27]:
vector_0_8 = np.arange(9)
matrix_3x3 = vector_0_8.reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3x3 identity matrix.

In [28]:
creat_identity_matrix = np.array([
    [1, 0, 0], [0, 1, 0], [0, 0, 1]
    ])
print(creat_identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [29]:
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:")
print(identity_matrix)

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a 3x3x3 array with random values.

In [30]:
random_array_3x3x3 = np.random.random((3, 3, 3))
print("3x3x3 Random array:")
print(random_array_3x3x3)

3x3x3 Random array:
[[[0.26681394 0.46076262 0.60238956]
  [0.18257676 0.87262904 0.64636953]
  [0.12878492 0.08877414 0.83795822]]

 [[0.94456833 0.03221474 0.22198298]
  [0.01839797 0.08348661 0.03467632]
  [0.03333106 0.25856762 0.65901288]]

 [[0.90791773 0.4052933  0.87059589]
  [0.0347946  0.86325701 0.58197915]
  [0.27981796 0.67016674 0.58971025]]]


5. Create a 10x10 array with random values and find the minimum and maximum values.

In [31]:
random_array_10x10 = np.random.random((10, 10))

min_val_10x10 = random_array_10x10.min()
max_val_10x10 = random_array_10x10.max()

print("10x10 Random array:")
print(random_array_10x10)

print("Min value:", min_val_10x10)
print("Max value:", max_val_10x10)

10x10 Random array:
[[0.38235151 0.8633933  0.27664073 0.21633185 0.74469788 0.03721879
  0.88709856 0.20901742 0.12520993 0.49237753]
 [0.79275472 0.05739217 0.7305316  0.15432977 0.57670629 0.42702584
  0.08862169 0.6409774  0.35118846 0.4568766 ]
 [0.73251579 0.22364375 0.44140749 0.18782675 0.51240718 0.66127732
  0.07295893 0.20029802 0.40446978 0.67622432]
 [0.81981191 0.68125502 0.41558782 0.70308247 0.31615883 0.01951259
  0.79360636 0.49379835 0.72671202 0.73461805]
 [0.3111336  0.23979776 0.28030935 0.47283053 0.77485352 0.65140018
  0.26353203 0.53137529 0.92348703 0.07555477]
 [0.03845554 0.14982458 0.05222908 0.47555281 0.27004042 0.7124461
  0.76032668 0.94326519 0.05294205 0.24829242]
 [0.64673168 0.64767343 0.05354037 0.44683678 0.54914456 0.83913492
  0.80874944 0.29313866 0.02227067 0.57040023]
 [0.52266478 0.52737125 0.83261076 0.9331019  0.98841911 0.72499003
  0.5286433  0.20577774 0.77801064 0.24142986]
 [0.12604026 0.31220228 0.03827808 0.62680052 0.88448278 0.68

6. Create a random vector of size 30 and find the mean value.

In [32]:
random_vector_30x = np.random.random(30)
mean_val = random_vector_30x.mean()
print(random_vector_30x)
print(mean_val)

[0.03457353 0.44917181 0.88771978 0.30242635 0.02136994 0.68104038
 0.24931429 0.26363761 0.02817059 0.96382276 0.42612434 0.76491704
 0.01456614 0.91776803 0.39285796 0.33435516 0.95270467 0.93085941
 0.96098175 0.42116028 0.56295448 0.20650775 0.42138474 0.20055547
 0.25270005 0.08134735 0.39553366 0.84482295 0.22282242 0.46040621]
0.45488589659611606


7. Normalize a 5x5 random matrix.


In [33]:
# 5x5 o'lchamli tasodifiy matritsa yaratamiz
random_matrix_5x5 = np.random.random((5, 5))

# Matritsani normallashtiramiz 
normalized_matrix = (random_matrix_5x5 - random_matrix_5x5.min())/(random_matrix_5x5.max() - random_matrix_5x5.min())

print("Tasodifiy 5x5 Matritsa:") 
print(random_matrix_5x5) 

print("Normallashtirilgan 5x5 Matritsa:") 
print(normalized_matrix)

Tasodifiy 5x5 Matritsa:
[[0.19029964 0.98128965 0.79642982 0.61492886 0.10989578]
 [0.00794832 0.73227993 0.97764546 0.32374115 0.67569342]
 [0.50292869 0.58034733 0.46015898 0.11056204 0.22197353]
 [0.26124232 0.56404134 0.91166336 0.53819285 0.33687019]
 [0.75685738 0.02644379 0.42840737 0.40223044 0.54014631]]
Normallashtirilgan 5x5 Matritsa:
[[0.1873457  1.         0.81007708 0.62360502 0.10473968]
 [0.         0.7441702  0.99625601 0.32444203 0.68603385]
 [0.50853729 0.58807635 0.46459618 0.10542419 0.21988711]
 [0.26023142 0.57132375 0.92846673 0.54476731 0.33793065]
 [0.7694208  0.01900204 0.43197492 0.40508104 0.54677426]]


8. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).


In [34]:
matrix_5x3 = np.random.random((5, 3))
matrix_3x2 = np.random.random((3, 2))

# Matritsalarni ko'paytishishda np.dot() funksiyasidan foydalaniz
matrix_product = np.dot(matrix_5x3, matrix_3x2)

print("5x3 Matritsa:") 
print(matrix_5x3) 
print("3x2 Matritsa:") 
print(matrix_3x2) 
print("Matritsa Mahsuloti (5x3 * 3x2):")
print(matrix_product)

5x3 Matritsa:
[[0.24027863 0.06565386 0.81461021]
 [0.7239432  0.9304981  0.73147811]
 [0.36702342 0.28190821 0.71203198]
 [0.87930441 0.60869586 0.6684775 ]
 [0.3429835  0.20650251 0.68588565]]
3x2 Matritsa:
[[0.02668763 0.86543796]
 [0.17530633 0.99336445]
 [0.73781575 0.23848438]]
Matritsa Mahsuloti (5x3 * 3x2):
[[0.61895425 0.46743627]
 [0.72213861 1.72529776]
 [0.58456368 0.76748209]
 [0.62338801 1.52506168]
 [0.55141185 0.66553621]]


9. Create two 3x3 matrices and compute their dot product.  

In [58]:
a =  np.random.random((3, 3))
b =  np.random.random((3, 3))

# Dot product
dot_product = np.dot(a, b)

print(f"""Matrix_1:
{a}

""")
print(f"""Matrix_2:   
{b}""")

Matrix_1:
[[0.09837726 0.77027176 0.35316424]
 [0.53761339 0.24827096 0.60104177]
 [0.90867409 0.16351638 0.24844545]]


Matrix_2:   
[[0.36159028 0.64266135 0.21325418]
 [0.77965216 0.76821571 0.86451417]
 [0.91688375 0.40728548 0.74769528]]


10. Given a 4x4 matrix, find its transpose.  


In [59]:
matrix_4x4 = np.random.random((4, 4))
transpose_matrix = np.transpose(matrix_4x4)

print("4x4 Matritsa:")
print(matrix_4x4)
print("Transpose of the 4x4 Matrix:")
print(transpose_matrix)

4x4 Matritsa:
[[0.21075952 0.427889   0.47821491 0.672334  ]
 [0.05270067 0.85189074 0.52220331 0.02354798]
 [0.54664753 0.69055819 0.38404277 0.54805144]
 [0.00626785 0.07458216 0.72760548 0.37742727]]
Transpose of the 4x4 Matrix:
[[0.21075952 0.05270067 0.54664753 0.00626785]
 [0.427889   0.85189074 0.69055819 0.07458216]
 [0.47821491 0.52220331 0.38404277 0.72760548]
 [0.672334   0.02354798 0.54805144 0.37742727]]


11. Create a 3x3 matrix and calculate its determinant.  


In [60]:
matrix_3x3_det = np.random.random((3, 3))
determinant = np.linalg.det(matrix_3x3_det)

print("3x3 Matritsa:")
print(matrix_3x3_det)
print("Determinant of the 3x3 Matrix:")
print(determinant)

3x3 Matritsa:
[[0.68561837 0.01897763 0.25405604]
 [0.31510135 0.59867049 0.32081638]
 [0.60539318 0.29120405 0.40858463]]
Determinant of the 3x3 Matrix:
0.036131525157000535


12. Create two matrices \( A \) (3x4) and \( B \) (4x3), and compute the matrix product \( A \cdot B \).  


In [61]:
matrix_A_3x4 = np.random.random((3, 4))
matrix_B_4x3 = np.random.random((4, 3))
matrix_product_AB = np.dot(matrix_A_3x4, matrix_B_4x3)

print("Matrix A (3x4):")
print(matrix_A_3x4)
print("Matrix B (4x3):")
print(matrix_B_4x3)
print("Matrix Product (A • B):")
print(matrix_product_AB)

Matrix A (3x4):
[[0.75306052 0.40840335 0.76809614 0.14217299]
 [0.72626616 0.77237428 0.20488333 0.71879339]
 [0.10028928 0.93291913 0.5560393  0.80893839]]
Matrix B (4x3):
[[0.41766628 0.71798118 0.88352854]
 [0.12777572 0.60716328 0.2045665 ]
 [0.56427032 0.18668185 0.28989994]
 [0.88089487 0.00326803 0.44126008]]
Matrix Product (A • B):
[[0.92536533 0.93250503 1.03430239]
 [1.15081856 1.03099977 1.17624927]
 [1.18743802 0.74488613 0.79760042]]


13. Create a 3x3 random matrix and a 3-element column vector. Compute the matrix-vector product.  


In [62]:
matrix_3x3_rnd = np.random.random((3, 3))
vector_3 = np.random.random(3)
matrix_vector_product = np.dot(matrix_3x3_rnd, vector_3)

print("3x3 Random Matrix:")
print(matrix_3x3_rnd)
print("3-element Column Vector:")
print(vector_3)
print("Matrix-Vector Product:")
print(matrix_vector_product)



3x3 Random Matrix:
[[0.76276796 0.42221647 0.60941413]
 [0.09835905 0.73317313 0.63876661]
 [0.94268985 0.84311447 0.13728264]]
3-element Column Vector:
[0.68607428 0.12786768 0.02139737]
Matrix-Vector Product:
[0.59034318 0.17489869 0.75749984]


14. Solve the linear system \( Ax = b \) where \( A \) is a 3x3 matrix, and \( b \) is a 3x1 column vector.  


In [64]:
A_3x3 = np.random.random((3, 3))
b_3x1 = np.random.random(3)
x = np.linalg.solve(A_3x3, b_3x1)

print("Matrix A (3x3):")
print(A_3x3)
print("Column Vector b (3x1):")
print(b_3x1)
print("Solution Vector x:")
print(x)


Matrix A (3x3):
[[1.24000911e-01 1.92846630e-04 3.47114588e-01]
 [5.47813959e-02 2.33989350e-01 9.42493754e-01]
 [9.95430066e-01 1.43781956e-01 1.11880413e-01]]
Column Vector b (3x1):
[0.42651792 0.47708005 0.59655523]
Solution Vector x:
[ 0.7779493  -1.97759536  0.95194175]


15. Given a 5x5 matrix, find the row-wise and column-wise sums.

In [63]:
matrix_5x5 = np.random.random((5, 5))
row_sums = matrix_5x5.sum(axis=1)
column_sums = matrix_5x5.sum(axis=0)

print("5x5 Matrix:")
print(matrix_5x5)
print("Row-wise Sums:")
print(row_sums)
print("Column-wise Sums:")
print(column_sums)


5x5 Matrix:
[[0.71083985 0.82487078 0.82101632 0.65871231 0.27834255]
 [0.21293462 0.55890108 0.84142253 0.14362986 0.7696953 ]
 [0.9162699  0.56839276 0.92470487 0.32037271 0.31362641]
 [0.18387756 0.92866637 0.26641613 0.35905799 0.07844341]
 [0.72946218 0.75382111 0.46418271 0.31306926 0.88025066]]
Row-wise Sums:
[3.29378182 2.5265834  3.04336665 1.81646146 3.14078592]
Column-wise Sums:
[2.75338411 3.6346521  3.31774257 1.79484213 2.32035833]
